# Site settings
title: kijalx's Blog

author:
  name: Aleksander Kijewski
  email: alekskijewski88@gmail.com
description: "A website."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme
